web/CourtCase/CourtCase/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('recommend.urls', namespace='recommend')),
]

web/CourtCase/recommend/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
	url(r'^$', views.index),
    url(r'^search/$', views.index, name='recommend_search'),
    url(r'^list/$', views.list, name='recommend_list'),
    url(r'^searchbykey/$', views.list, name='search_list'),
    url(r'^display/(?P<case_id>[0-9a-z]+)$', views.display, name='recommend_display'),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/CourtCase/recommend/models.py
from django.db import models

# Create your models here.

web/CourtCase/recommend/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .Core import CaseStatutesRecommend
from .collections import AllInfoCol


def index(request):
    return render(request, 'recommend/index.html')


def list_format(case_ids):
    # res = []
    # aic = AllInfoCol()
    #
    # for cid in case_ids:
    #     cs = aic.getSummary(cid)
    #     res.append({
    #         'id' : cid,
    #         'title' : cs,
    #     })

    res = [
        {
            'id' : '5a35c06f0e2c815b200b0809',
            'title' : '高某某婚约财产纠纷一案',
            'court' : '安徽省濉溪县人民法院',
            'time' : '2014',
            'keywords' : '彩礼 媒人 返还 解除婚约 收取 关系 婚约 相处 未果 过程',
            'causeOfAction' : '婚约财产纠纷'},
        {
            'id': '5a33abf30e2c810b3c383eca',
            'title': '刘某甲与郭某甲婚约财产纠纷一案',
            'court': ' 河南省睢县人民法院',
            'time': '2014',
            'keywords': '现金 回来 结婚仪式 所送 返还 彩礼 举行',
            'causeOfAction': '婚约财产纠纷'},
        {
            'id': '5a34608d0e2c810b3cd89d0e',
            'title': '张某甲与杨某某、张某乙等婚约财产纠纷一案',
            'court': ' 山东省临沭县人民法院',
            'time': '2014',
            'keywords': '衣服 摩托车 三金 财物 风俗 农村 结婚仪式 现金',
            'causeOfAction': '婚约财产纠纷'},
        {
            'id': '5a340d410e2c810b3c8de405',
            'title': '陈某与张某丙、张某乙等婚约财产纠纷一案',
            'court': '浙江省绍兴市越城区人民法院',
            'time': '2015',
            'keywords': '订婚 彩礼 金器 终止 证书 因故 仪式 返还',
            'causeOfAction': '婚约财产纠纷'},
    ]

    return res


def list(request):
    result = {}
    page_limit = 8
    query = str(request.GET.get('key'))
    print(query)

    # csr = CaseStatutesRecommend(query)
    # case_list, statutes_list = csr.recommend()

    case_list, statutes_list = [1,2,3], ['《最高人民法院关于适用〈中华人民共和国婚姻法〉若干问题解释（二）》第十条', '《中华人民共和国婚姻法》第三条','《中华人民共和国民事诉讼法》第一百四十四条', '《中华人民共和国民事诉讼法》第二百五十三条']
    pre_cases = list_format(case_list)

    paginator = Paginator(pre_cases, page_limit)

    page = request.GET.get('page', 1)

    try:
        cases = paginator.page(page)
    except PageNotAnInteger:
        cases = paginator.page(1)
    except EmptyPage:
        cases = paginator.page(paginator.num_pages)

    result['query'] = query
    result['cases'] = cases
    result['cases_num'] = len(cases)
    result['isPaging'] = len(pre_cases) > 6
    result['key'] = query
    result['statutes'] = statutes_list

    return render(request, 'recommend/list.html', result)


def display(request, case_id):
    result = {}

    # aic = AllInfoCol()
    # case = aic.getAllInfo(case_id)

    case = dict()
    case['caseplaintiffAlleges'] = '原告诉称：原、被某某于2015年1月18日举行结婚仪式，但未办理登记手续，后被某某于次日2015年1月19日，双方因家庭琐事发生口角，被某某回娘家，至今未回，原告于当日去娘家接被某某，被某某以种种理由拒不回家。原告认为，被某某刚举行结婚仪式一天便回娘家不归，其行为纯属于骗取原告彩礼款，故原告诉讼来院，要求1、被某某返还彩礼款及其他款共计18万元；2、案件受理费由被某某承担。'
    case['defendantArgued'] = '被某某辩称：2015年1月18日结婚，第二天早上，给我的压腰钱，原告向我要，我不给，原告的父母就把我们的结婚相给摔了，还把我打了，之后我就住院了，后来我就回娘家了，原告没有给我过18万元的彩礼，我没有骗婚。'
    case['factFound'] = '经审理查明：原、被某某双方经人介绍后，于2015年1月18日举行结婚仪式，但未进行婚姻登记。后于结婚仪式第二天即2015年1月19日，原、被某某因家庭琐事发生口角，被某某返回娘家至今未归。原告在举行结婚仪式前分两次先后给付被某某2万元、14万元彩礼款，原告向被某某索要彩礼款，被某某表示拒绝。'
    case['analysisProcess'] = '本院认为，1、自举行结婚仪式时起原、被某某之间就建立了婚约关系，最终双方无法缔结婚姻关系。依据《最高人民法院关于适用﹤中华人民共和国婚姻法﹥若干问题解释（二）》的相关规定，如果双方未办理结婚登记手续的，一方当事人请求另一方返还按照习俗给付的彩礼的，人民法院应当予以支持；2、原告主张其给付被某某彩礼16万元、一条金项链价值1万元，小包钱2000元及结婚当天给被某某的戴花钱1万元，故要求被某某返还彩礼共计18万元。并提供证人杜桂兰（媒人杜某甲作证，但庭审中证人杜桂兰表示其杜某甲付彩礼的过程，仅知道原告向被某某给付彩礼共人民币16万元，故原告提供的证据不能支持其向被某某给付的彩礼为18万元的主张。3、彩礼一般是指男女一方基于婚约关系，按照当地风俗习惯给付另一方数额较大的财物。综上，结合证人证言应确定原告向被某某给付的彩礼为人民币16万元。考虑被某某与原告已共同生活，且因家庭琐事导致双方最终无法缔结婚姻关系，故酌情确定被某某应向原告返还彩礼13万元为宜。 依照《中华人民共和国婚姻法》第三条、《最高人民法院关于适用﹤中华人民共和国婚姻法﹥若干问题的解释（二）》第十条第一款第（一）项之规定，判决如下：'
    case['caseDecision'] = '被某某王某某于判决生效后立即返还原告高某某彩礼款人民币130，000．00元。 如果未按本判决指定的期间履行给付金钱义务，应当按照《中华人民共和国民事诉讼法》第二百五十三条之规定，加倍支付迟延履行期间的债务利息。 案件受理费3，900．00元，由被某某承担。 如不服本判决，可在判决书送达之日起十五日内，向本院提交上诉状并按对方当事人的人数提出副本，上诉于吉林省长春市中级人民法院。'

    content = ''
    if case['caseplaintiffAlleges']:
        content += '  ' + case['caseplaintiffAlleges'] + '\n\n'
    if case['defendantArgued']:
        content += '  ' + case['defendantArgued'] + '\n\n'
    if case['factFound']:
        content += '  ' + case['factFound'] + '\n\n'
    if case['analysisProcess']:
        content += '  ' + case['analysisProcess'] + '\n\n'
    if case['caseDecision']:
        content += '  ' + case['caseDecision'] + '\n'

    result['case'] = dict(
        title = '高某某婚约财产纠纷一案',
        causeOfAction = '婚约财产纠纷',
        file = '吉林省农安县人民法院 民事判决书 （2015）农民初字第341号',
        content = content,
    )

    return render(request, 'recommend/display.html', result)

web/CourtCase/recommend/templates/recommend/base.html
<!DOCTYPE html>
<html>
<head>
	<title>index</title>
	{% include "recommend/load.html" %}
	{% load static %}

	<link rel="stylesheet" type="text/css" href="{% static "recommend/css/base.css" %}">
	{% block css %}
	{% endblock %}

</head>

<body>
	<header>
		<div class="row">
			<div class="col-xs-11 col-md-offset-1 row" >		
			</div>
		</div>
	</header>

	<div id="mainbody">
			{% block mainbody %}{% endblock %}
	</div>

	<footer>
		<div>
			南京大学版权所有
		</div>
	</footer>
</body>

</html>

web/CourtCase/recommend/templates/recommend/display.html
{%  extends "recommend/base.html" %}
{% load string_filter %}

{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static "recommend/css/display.css" %}">
{% endblock %}

{% block mainbody %}
	<div class="row">
		<div class="col-xs-8 col-md-offset-2" id="outer">	
			<div class="row">
				<div class="col-xs-12" id="title">
					<h1>{{ case.title }}</h1>
				</div>
				<div id="tag">
					<p>{{ case.file }}</p>
				</div>
				<div id="info">
					{{ case.content|linebreaksbr}}
				</div>
			</div>
		</div>
	</div>
{% endblock %}

web/CourtCase/recommend/templates/recommend/index.html
{%  extends "recommend/base.html" %}

{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static "recommend/css/index.css" %}">
{% endblock %}

{% block mainbody %}

<div class="container">
	<div class="row" id="classify-list">
		<nav class="navbar navbar-default col-xs-10 col-md-offset-1" role="navigation">
			<div class="container-fluid"> 
				<div>
					<ul class="nav navbar-nav row col-md-12">
						<li class="col-md-3 classify-list-elemnet"><a href="#">首页</a></li>
						<li class="col-md-3  classify-list-elemnet"><a href="#">刑事案件</a></li>
						<li class="col-md-3  classify-list-elemnet"><a href="#">民事案件</a></li>
						<li class="col-md-3  classify-list-elemnet"><a href="#">行政案件</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</div>	
	<div class="row" id="search-bar">
		<div class="col-md-12">
			<form class="input-group col-xs-8 col-md-offset-2"  action="{% url 'recommend:search_list' %}" method="get">
				{% csrf_token %}
				<div class="row">
					<label class="col-sm-2 control-label form-label">案由：</label>
					<div class="col-sm-5">
						<select id="select" name="select" class="selectpicker show-tick form-control">
						  	<option value="-1">自动</option>
							<option value="0">人格权纠纷</option>
							<option value="1">婚姻家庭、继承纠纷</option>
							<option value="2">物权纠纷</option>
							<option value="3">合同、无因管理、不当得利纠纷</option>
							<option value="4">知识产权与竞争纠纷</option>
							<option value="5">劳动争议、人事纠纷</option>
							<option value="6">海事海商纠纷</option>
							<option value="7">公司、证券、保险、票据有关纠纷</option>
							<option value="8">侵权责任纠纷</option>
							<option value="9">适用特殊程序案件案由</option>
						</select>
					</div>
				</div>
				<div class="row">
					<label class="col-sm-2 control-label form-label">案情：</label>
					<div class="col-sm-10">
						<textarea id="info" class="form-control" rows="8" name="info"></textarea>
					</div>
				</div>
				<div class="row" style="margin-top:20px;">
					<button class="btn col-sm-2 col-md-offset-6" id="search-bar-submit" type="submit">查询</button>
				</div>
    		</form>
		</div>
	</div>	
</div>
{% endblock %}

web/CourtCase/recommend/templates/recommend/list.html
{%  extends "recommend/base.html" %}

{% load static %}

{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static "recommend/css/list.css" %}">
{% endblock %}

{% block mainbody %}
<div class="row" id="container">
	<div class=" col-md-3" style="padding-top:0px">
		<div class="" style="margin-top:0px; padding-bottom:20px; background-color:#ffffff">
			<div style="height:70px; padding:5px 25px;">
				<h3>适用法条预测</h3>
			</div>
			<ul>
				{% for statute in statutes %}
				<li>
					<p>{{statute}}</p>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="col-md-9 row" id="list">
		{% for case in cases %}
		<div class="col-xs-12" id="each_li">
			<div class="row">
				<div class="col-xs-12 title">
					<h1 style="padding: 0px"><a href="{% url 'recommend:recommend_display' case.id %}">{{ case.title }}</a></h1>
				</div>
				<div class="col-xs-12 desc">
					<p>{{case.court}}&nbsp;&nbsp;&nbsp;{{case.time}}</p>
				</div>
				<div class="col-xs-12 summary">
					<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp;&nbsp;{{ case.keywords }}
				</div>
				<div class="col-xs-3" style="color:#1b6ac2; margin-top:5px">
					<span class="glyphicon glyphicon-tag" aria-hidden="true"></span>&nbsp;{{case.causeOfAction}}
				</div>
				<div class="col-xs-3 col-md-offset-6 link">
					<a class="btn btn-link" role="button" href="{% url 'recommend:recommend_display' case.id %}">详情<span class="glyphicon glyphicon-menu-right" style=""></span></a>
				</div>
			</div>
		</div>
		{% endfor %}

		{% if isPaging %}
			<nav class="col-xs-5 col-md-offset-4" aria-label="Page navigation">
				<ul class="pagination">
					<li>
					{% if cases.has_previous %}
						<a href="?page={{ cases.previous_page_number }}&key={{ key }}" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
						</a>
					{% else %}
						<a href="#" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
						</a>
					{% endif %}
					</li>
  			
  					{% for page_number in cases.paginator.page_range %}
    				{% ifequal page_number cases.number %}
      				<li><a href="#">{{ page_number }}</a></li>
    				{% else %}
      				<li><a href="?page={{ page_number }}&key={{ key }}">{{ page_number }}</a></li>
    				{% endifequal %}
  					{% endfor %}


  					<li>
  					{% if cases.has_next %}
						<a href="?page={{ cases.next_page_number }}&key={{ key }}" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					{% else %}
						<a href="#" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						</a>
					{% endif %}
					</li>
				</ul>
			</nav>
		{% endif %}
	</div>
</div>
{% endblock %}

web/CourtCase/recommend/templates/recommend/load.html
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

web/CourtCase/recommend/templates/recommend/testResult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试效果展示</title>

    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>

</head>
<body>
<div style="height:50px"></div>
<div class="row">
    <div class="col-md-2" style="margin: 0px 20px">
        <ul class="nav nav-pills nav-stacked" id="leftNav">
            <li role="presentation" class="active"><a style="cursor:default">tag2</a></li>
            <li role="presentation"><a style="cursor:default">tag3</a></li>
            <li role="presentation"><a style="cursor:default">tag4</a></li>
        </ul>
    </div>
    <div class="col-md-9">
        <ul class="nav nav-tabs" id="topNav" style="margin: 0px 50px">
            <li id="1" class="chart" style="margin-left: 5%"><a style="cursor:default">top1</a></li>
            <li id="3" class="chart"><a style="cursor:default">top3</a></li>
            <li id="5" class="chart"><a style="cursor:default">top5</a></li>
            <li id="10" class="chart"><a style="cursor:default">top10</a></li>
            <li id="20" class="chart"><a style="cursor:default">top20</a></li>
            <li id="50" class="chart"><a style="cursor:default">top50</a></li>
        </ul>

        <div id="container1" style="width: 100%; height: 550px; margin: 0 auto"></div>
        <div id="container2" style="width: 100%; height: 550px; margin: 0 auto"></div>
        <div id="container3" style="width: 100%; height: 550px; margin: 0 auto"></div>
    </div>
</div>

<script language="JavaScript">
$(document).ready(function(){
    $("#leftNav li").click(function(){
        if($(this).hasClass('active')){
            return;
        }
        else{
            $("#leftNav .active").removeClass("active");
            $(this).addClass("active");
        }
    });

    $(".chart").click(function(){
        if($(this).hasClass('active')){
            return;
        }
        else{
            $("#topNav .active").removeClass("active");
            $(this).addClass("active");
            $('#container1').html('');
            $('#container2').html('');
            $('#container3').html('');

            var tag = $("#leftNav li").index($("li.active"));

            var limit = $(this).attr('id');

            $.getJSON("{% url 'recommend:statutePRF' %}", {
                        limit: limit,
			            tag: tag
                    },function(ret){
                    chart1 = setMeanPRFChart(ret.tName, ret.sortPrecisionList, ret.noSortPrecisionList, '法条效果展示-precision');
                    chart2 = setMeanPRFChart(ret.tName, ret.sortRecallList, ret.noSortRecallList, '法条效果展示-recall');
                    chart3 = setMeanPRFChart(ret.tName, ret.sortF1List, ret.noSortF1List, '法条效果展示-f1');
                    $('#container1').highcharts(chart1);
                    $('#container2').highcharts(chart2);
                    $('#container3').highcharts(chart3);
                });
        }
    });
});


function setMeanPRFChart(x, sortData, data, title)
{
    var chart = {
        title : {
            text: title,
        },
        xAxis : {
            title: {
                text: '策略'
            },
            categories: x,
            crosshair: true,
        },
        yAxis : {
            title: {
                text: 'rate'
            }
        },
        tooltip : {
            enabled: true,
            formatter: function() {
            return '<b>'+ this.y;
            }
        },
        legend : {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series : [{
                    name: '上限',
                    data: sortData,
                   },
                  {
                    name: '测试值',
                    data: data,
                   }
                   ],
    }
    return chart
}
</script>

</body>
</html>